### ISSUE TITLE
Check if there's any name change of the stations

### ISSUE THREAD

**Issue by vegahi** [vegahi/thesis#14]

**Comment by vegahi** [comment]
I used the following queries to check for if there's any duplicate names for the same station ID and didn't find any. The number of rows of the returned table is the same as the number of unique stations, both for start (662) and end (689) stations.

````
SELECT Start_Station_ID, Start_Station_Name, Start_Station_Latitude, Start_Station_Longitude FROM
citibike.trips GROUP BY Start_Station_ID ORDER BY max(Start_Station_Name) DESC;

SELECT End_Station_ID, End_Station_Name, End_Station_Latitude, End_Station_Longitude FROM 
citibike.trips GROUP BY End_Station_ID ORDER BY max(End_Station_Name) DESC;
````

**Comment by beanumber** [comment]
I don't think this quite does it though. I think you want something more like:
```
SELECT Start_Station_ID, count(distinct Start_Station_Name) as N
FROM citibike.trips 
GROUP BY Start_Station_ID
HAVING N > 1;
```

**Comment by vegahi** [comment]
1. For the names, some of them are completely different while others are minor changes (order, abbreviation or space):
````
Joralemon St & Adams St, Cadman Plaza W & Pierrepont St
Mobile 01,Kent Ave & N 7 St
Kent Ave & N 7 St,KentAve&N7 St
78 St & 2 Ave,E 78 St & 2 Ave
Shevchenko Pl & E 6 St,Shevchenko Pl & E 7 St
Allen St & E Houston St,Allen St & Stanton St
````
If that's the case, can I export the tables and make changes manually and then save into the database? 
- For  completely different names, keep the most recent.
- For the order flipping ones, rewrite according to Street & Avenue.
- For others, I will choose the most complete form of names

2. I also checked for the longitude column
````
SELECT DISTINCT
Start_Station_ID, count(distinct Start_Station_Longitude) as N,
 GROUP_CONCAT(DISTINCT Start_Station_Longitude ORDER BY Start_Station_Longitude)
FROM citibike.trips
GROUP BY Start_Station_ID
HAVING N>1;

Start_Station_ID,N,"GROUP_CONCAT(DISTINCT Start_Station_Longitude ORDER BY Start_Station_Longitude)"
151,3,"-73.99724900722504,-73.997249007225,-73.99720307"
153,2,"-73.9816324043,-73.9816324"
160,2,"-73.978311,-73.978238"
173,2,"-73.9845272898674,-73.98442659"
228,2,"-73.97187886,-73.971878855"
233,3,"-73.99052739143372,-73.99052739,-73.98963911"
242,2,"-73.973736,-73.97350332"
243,2,"-73.979382,-73.978474"
262,2,"-73.9737299,-73.97372989"
263,2,"-73.996375,-73.99622440338135"
271,2,"-73.97805813,-73.97800147533417"
279,2,"-74.00167,-73.98271933"
282,3,"-73.96841526031494,-73.9684152603149,-73.96834101"
284,2,"-74.0026376103,-74.00263761"
````
I can't really tell if the different decimal places are because of accuracy problem or actual location changes. I could try to extract the other  `Latitude` column and plot all the both of them on the plots. However, I don't know if that's worth doing. Or should I just go will the most accurate records (with the longest digits)?

3. The other thing is that, the number of distinct names for station ids is 32. However, the number of distinct longitude for station ids is 85 and the number of distinct latitude for station ids is 84.

@beanumber

**Comment by beanumber** [comment]
I don't think the names matter so much, because those are just arbitrary labels. Do you know about `CREATE TABLE`?

You can try to:
```
CREATE TABLE stations 
  SELECT Start_Station_ID, 
    count(distinct Start_Station_Longitude) as N,
    max(Start_Station_Name) as station_name,
    GROUP_CONCAT(DISTINCT Start_Station_Name) as all_names
  FROM citibike.trips
  GROUP BY Start_Station_ID
```
This way you settle on one name to use, but you capture all of the names in case there is any confusion. 

The locations is trickier. Some of the errors definitely look like rounding errors, which you can safely ignore, but for others it is not so clear. If you think they are sufficiently close you could try taking the average. (?)

**Comment by vegahi** [comment]
If I want to create the station table with columns `id`,`name`,`all_names`, `avg_longitude` and `avg_latitude`, can I first get the information of the start stations and stop stations and then join the tables together? (What would be a good way to join them together?)

I tried to run the following code. However, the execution time was too long and the connection got expired.
````
  CREATE TABLE start_stations 
  SELECT Start_Station_ID,
    max(Start_Station_Name) as station_name,
    GROUP_CONCAT(DISTINCT Start_Station_Name) as all_names,
    avg(Start_Station_Longitude) as longitude,
    avg(Start_Station_Latitude) as latitude
  FROM citibike.trips
  GROUP BY Start_Station_ID; 
````
