### ISSUE TITLE
what exactly are we modeling here?

### ISSUE THREAD

**Issue by beanumber** [vegahi/thesis#15]

**Comment by beanumber** [comment]
What are the inputs to your model?
What is the output of your model?
How will we judge its effectiveness?
What is the goal? Prediction? Understanding the system? 
Can you beat a simple MLR model?

**Comment by vegahi** [comment]
I created the `trip_netflow` table in the database. However, I could not view it in MySQL or R. Is the query still being processed? Or because there are too many tables under citibike? Does it work for you? @beanumber

**Comment by vegahi** [comment]
I added index to the start station id and end station id column. I also sent the query last night and still could not get the result back at this moment.

**Comment by vegahi** [comment]
I killed the old query and tried the following:
```
CREATE TABLE trips_netflow
(ID INT,
the_year INT,
the_month INT,
the_day INT,
the_hour INT,
netflow INT,
INDEX `index_ID` (`ID`)
)
SELECT Start_Station_ID as ID, a.the_year, a.the_month, a.the_day, a.the_hour, (trips_out-trips_in) as netflow
FROM citibike.trips_out a
INNER JOIN
citibike.trips_in b
on (a.Start_Station_ID = b.End_Station_ID AND a.the_year = b.the_year AND a.the_month = b.the_month AND 
a.the_day = b.the_day AND a.the_hour = b.the_hour);

```

**Comment by beanumber** [comment]
In your SELECT query above, you are SELECTing from `trips_out` and `trips_in`, but you haven't created any indexes on those tables. 

Also, check the query with EXPLAIN to see how many rows will be involved before actually trying to run it.
