### ISSUE TITLE
create "init.R" script

### ISSUE THREAD

**Issue by beanumber** [vegahi/thesis#2]
That will populate scidb with the exact set of data that you will be using in this project. I'd suggest:

* getting it to work for just one month
* then extend to one year
* then extend for the full period up until the end of 2016

**Comment by vegahi** [comment]
Where should the `init.R` go? In Vignettes?

**Comment by beanumber** [comment]
Anywhere in the thesis repo is fine.

**Comment by vegahi** [comment]
I uploaded the `init.Rmd` file, but it doesn't have the code output. Would you it be necessary to include the `init.html`? However, processing the file takes pretty long time. Could you also take a look at  `init.Rmd` and let me know if there's anything that I missed?
