### ISSUE TITLE
compute basic summary statistics

### ISSUE THREAD

**Issue by beanumber** [vegahi/thesis#5]
* How many bikes per day? 
* How many stations? 
* What is the distribution of bike volume across stations? 
* How many bikes per hour? 
* Which station has the greatest imbalance?

**Comment by beanumber** [comment]
* breakdown of `usertype`
* breakdown of `gender`
* distribution of number of trips per unique `bikeid`

**Comment by beanumber** [comment]
```
SELECT year(starttime) as the_year, month(starttime) as the_month, sum(1) as N FROM citibike.trips GROUP BY the_month, the_year;
```

**Comment by vegahi** [comment]
I added more things into the summary statistics under the appendix in  `thesis_draft.Rnw`. Knitting the whole file took around 3 hours and the last couple of code chunks were not able to be executed due to the lost of connection to the database. Might it be possible to walk around this problem?

**Comment by beanumber** [comment]
Yes. I can show you how to use a makefile to segment out the slow-to-compile parts.

**Comment by beanumber** [comment]
```
all: main.pdf

main.pdf: hitting.tex main.tex references.bib
	pdflatex main
	bibtex main
	pdflatex main
	bibtex main
	pdflatex main

clean: 
	rm *.idx *.ilg *.ind
	
hitting.tex: hitting.Rnw
	Rscript -e "library(knitr); knit('hitting.Rnw')"
```
