### ISSUE TITLE
Set up LaTeX template for thesis

### ISSUE THREAD

**Issue by beanumber** [vegahi/thesis#7]
Can you do this as an `.Rnw`? That would be awesome!

Ask Sara S. for LaTeX template if you can't get one from the library.

**Comment by beanumber** [comment]
See also: https://github.com/ismayc/reedtemplates

**Comment by vegahi** [comment]
Sara just shared her template with me :)

**Comment by beanumber** [comment]
Great. Feel free to close this issue then.
