### ISSUE TITLE
conduct literature review

### ISSUE THREAD

**Issue by beanumber** [vegahi/thesis#8]
include:

* any scholarly papers written about the CitiBike data
* relevant scholarly papers written about bike-sharing programs in general
* material relevant to `etl`, `dplyr`, `DBI`, etc.
* brief section on reproducibile research

**Comment by beanumber** [comment]
Make sure to cite the works of Shmoys & Mohany:
http://www.news.cornell.edu/stories/2015/01/cornell-research-steers-nyc-bikes-needy-stations

**Comment by beanumber** [comment]
Also, add citations for major R packages used, such as `etl`, `dplyr`, `shiny`, `lubridate`, `knitr`, `markdown`, as well as R itself. 

Use `citation("etl")` to get the BibTeX entries!

**Comment by beanumber** [comment]
Your paragraph about reproducible research should have citations as well, including Yihui's book about `knitr`. See my R Markdown paper for other possible citations.

**Comment by vegahi** [comment]
Just want to make sure these are the resources that you are referring to:
- RMarkdown: Integrating a reproducible analysis tool into introductory statistics
- Dynamic Documents with R and knitr

**Comment by beanumber** [comment]
Yes
